/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserUpdateInput } from "./UserUpdateInput";
import { UserUpdateInputCountArgs } from "./UserUpdateInputCountArgs";
import { UserUpdateInputFindManyArgs } from "./UserUpdateInputFindManyArgs";
import { UserUpdateInputFindUniqueArgs } from "./UserUpdateInputFindUniqueArgs";
import { DeleteUserUpdateInputArgs } from "./DeleteUserUpdateInputArgs";
import { UserUpdateInputService } from "../userUpdateInput.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserUpdateInput)
export class UserUpdateInputResolverBase {
  constructor(
    protected readonly service: UserUpdateInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "read",
    possession: "any",
  })
  async _userUpdateInputsMeta(
    @graphql.Args() args: UserUpdateInputCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserUpdateInput])
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "read",
    possession: "any",
  })
  async userUpdateInputs(
    @graphql.Args() args: UserUpdateInputFindManyArgs
  ): Promise<UserUpdateInput[]> {
    return this.service.userUpdateInputs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserUpdateInput, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "read",
    possession: "own",
  })
  async userUpdateInput(
    @graphql.Args() args: UserUpdateInputFindUniqueArgs
  ): Promise<UserUpdateInput | null> {
    const result = await this.service.userUpdateInput(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserUpdateInput)
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "delete",
    possession: "any",
  })
  async deleteUserUpdateInput(
    @graphql.Args() args: DeleteUserUpdateInputArgs
  ): Promise<UserUpdateInput | null> {
    try {
      return await this.service.deleteUserUpdateInput(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
