/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserUpdateInputService } from "../userUpdateInput.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserUpdateInputCreateInput } from "./UserUpdateInputCreateInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { UserUpdateInputFindManyArgs } from "./UserUpdateInputFindManyArgs";
import { UserUpdateInputWhereUniqueInput } from "./UserUpdateInputWhereUniqueInput";
import { UserUpdateInputUpdateInput } from "./UserUpdateInputUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserUpdateInputControllerBase {
  constructor(
    protected readonly service: UserUpdateInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserUpdateInput })
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserUpdateInput(
    @common.Body() data: UserUpdateInputCreateInput
  ): Promise<UserUpdateInput> {
    return await this.service.createUserUpdateInput({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserUpdateInput] })
  @ApiNestedQuery(UserUpdateInputFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userUpdateInputs(
    @common.Req() request: Request
  ): Promise<UserUpdateInput[]> {
    const args = plainToClass(UserUpdateInputFindManyArgs, request.query);
    return this.service.userUpdateInputs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserUpdateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userUpdateInput(
    @common.Param() params: UserUpdateInputWhereUniqueInput
  ): Promise<UserUpdateInput | null> {
    const result = await this.service.userUpdateInput({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserUpdateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserUpdateInput(
    @common.Param() params: UserUpdateInputWhereUniqueInput,
    @common.Body() data: UserUpdateInputUpdateInput
  ): Promise<UserUpdateInput | null> {
    try {
      return await this.service.updateUserUpdateInput({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserUpdateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserUpdateInput",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserUpdateInput(
    @common.Param() params: UserUpdateInputWhereUniqueInput
  ): Promise<UserUpdateInput | null> {
    try {
      return await this.service.deleteUserUpdateInput({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
