/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MessageDto } from "../../anonymousMessaging/MessageDto";
import { MessageDtoCountArgs } from "./MessageDtoCountArgs";
import { MessageDtoFindManyArgs } from "./MessageDtoFindManyArgs";
import { MessageDtoFindUniqueArgs } from "./MessageDtoFindUniqueArgs";
import { DeleteMessageDtoArgs } from "./DeleteMessageDtoArgs";
import { MessageDtoService } from "../messageDto.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MessageDto)
export class MessageDtoResolverBase {
  constructor(
    protected readonly service: MessageDtoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MessageDto",
    action: "read",
    possession: "any",
  })
  async _messageDtosMeta(
    @graphql.Args() args: MessageDtoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MessageDto])
  @nestAccessControl.UseRoles({
    resource: "MessageDto",
    action: "read",
    possession: "any",
  })
  async messageDtos(
    @graphql.Args() args: MessageDtoFindManyArgs
  ): Promise<MessageDto[]> {
    return this.service.messageDtos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MessageDto, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MessageDto",
    action: "read",
    possession: "own",
  })
  async messageDto(
    @graphql.Args() args: MessageDtoFindUniqueArgs
  ): Promise<MessageDto | null> {
    const result = await this.service.messageDto(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MessageDto)
  @nestAccessControl.UseRoles({
    resource: "MessageDto",
    action: "delete",
    possession: "any",
  })
  async deleteMessageDto(
    @graphql.Args() args: DeleteMessageDtoArgs
  ): Promise<MessageDto | null> {
    try {
      return await this.service.deleteMessageDto(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
