/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserInterestDto } from "../../anonymousMessaging/UserInterestDto";
import { UserInterestDtoCountArgs } from "./UserInterestDtoCountArgs";
import { UserInterestDtoFindManyArgs } from "./UserInterestDtoFindManyArgs";
import { UserInterestDtoFindUniqueArgs } from "./UserInterestDtoFindUniqueArgs";
import { DeleteUserInterestDtoArgs } from "./DeleteUserInterestDtoArgs";
import { UserInterestDtoService } from "../userInterestDto.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserInterestDto)
export class UserInterestDtoResolverBase {
  constructor(
    protected readonly service: UserInterestDtoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserInterestDto",
    action: "read",
    possession: "any",
  })
  async _userInterestDtosMeta(
    @graphql.Args() args: UserInterestDtoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserInterestDto])
  @nestAccessControl.UseRoles({
    resource: "UserInterestDto",
    action: "read",
    possession: "any",
  })
  async userInterestDtos(
    @graphql.Args() args: UserInterestDtoFindManyArgs
  ): Promise<UserInterestDto[]> {
    return this.service.userInterestDtos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserInterestDto, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserInterestDto",
    action: "read",
    possession: "own",
  })
  async userInterestDto(
    @graphql.Args() args: UserInterestDtoFindUniqueArgs
  ): Promise<UserInterestDto | null> {
    const result = await this.service.userInterestDto(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserInterestDto)
  @nestAccessControl.UseRoles({
    resource: "UserInterestDto",
    action: "delete",
    possession: "any",
  })
  async deleteUserInterestDto(
    @graphql.Args() args: DeleteUserInterestDtoArgs
  ): Promise<UserInterestDto | null> {
    try {
      return await this.service.deleteUserInterestDto(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
