/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { NotificationCreateInputService } from "../notificationCreateInput.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotificationCreateInputCreateInput } from "./NotificationCreateInputCreateInput";
import { NotificationCreateInput } from "./NotificationCreateInput";
import { NotificationCreateInputFindManyArgs } from "./NotificationCreateInputFindManyArgs";
import { NotificationCreateInputWhereUniqueInput } from "./NotificationCreateInputWhereUniqueInput";
import { NotificationCreateInputUpdateInput } from "./NotificationCreateInputUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class NotificationCreateInputControllerBase {
  constructor(
    protected readonly service: NotificationCreateInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: NotificationCreateInput })
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createNotificationCreateInput(
    @common.Body() data: NotificationCreateInputCreateInput
  ): Promise<NotificationCreateInput> {
    return await this.service.createNotificationCreateInput({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [NotificationCreateInput] })
  @ApiNestedQuery(NotificationCreateInputFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notificationCreateInputs(
    @common.Req() request: Request
  ): Promise<NotificationCreateInput[]> {
    const args = plainToClass(
      NotificationCreateInputFindManyArgs,
      request.query
    );
    return this.service.notificationCreateInputs({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: NotificationCreateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async notificationCreateInput(
    @common.Param() params: NotificationCreateInputWhereUniqueInput
  ): Promise<NotificationCreateInput | null> {
    const result = await this.service.notificationCreateInput({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: NotificationCreateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateNotificationCreateInput(
    @common.Param() params: NotificationCreateInputWhereUniqueInput,
    @common.Body() data: NotificationCreateInputUpdateInput
  ): Promise<NotificationCreateInput | null> {
    try {
      return await this.service.updateNotificationCreateInput({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: NotificationCreateInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteNotificationCreateInput(
    @common.Param() params: NotificationCreateInputWhereUniqueInput
  ): Promise<NotificationCreateInput | null> {
    try {
      return await this.service.deleteNotificationCreateInput({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
