/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotificationCreateInput } from "./NotificationCreateInput";
import { NotificationCreateInputCountArgs } from "./NotificationCreateInputCountArgs";
import { NotificationCreateInputFindManyArgs } from "./NotificationCreateInputFindManyArgs";
import { NotificationCreateInputFindUniqueArgs } from "./NotificationCreateInputFindUniqueArgs";
import { DeleteNotificationCreateInputArgs } from "./DeleteNotificationCreateInputArgs";
import { NotificationCreateInputService } from "../notificationCreateInput.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => NotificationCreateInput)
export class NotificationCreateInputResolverBase {
  constructor(
    protected readonly service: NotificationCreateInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "read",
    possession: "any",
  })
  async _notificationCreateInputsMeta(
    @graphql.Args() args: NotificationCreateInputCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [NotificationCreateInput])
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "read",
    possession: "any",
  })
  async notificationCreateInputs(
    @graphql.Args() args: NotificationCreateInputFindManyArgs
  ): Promise<NotificationCreateInput[]> {
    return this.service.notificationCreateInputs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => NotificationCreateInput, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "read",
    possession: "own",
  })
  async notificationCreateInput(
    @graphql.Args() args: NotificationCreateInputFindUniqueArgs
  ): Promise<NotificationCreateInput | null> {
    const result = await this.service.notificationCreateInput(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NotificationCreateInput)
  @nestAccessControl.UseRoles({
    resource: "NotificationCreateInput",
    action: "delete",
    possession: "any",
  })
  async deleteNotificationCreateInput(
    @graphql.Args() args: DeleteNotificationCreateInputArgs
  ): Promise<NotificationCreateInput | null> {
    try {
      return await this.service.deleteNotificationCreateInput(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
