/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InterestService } from "../interest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InterestCreateInput } from "./InterestCreateInput";
import { Interest } from "./Interest";
import { InterestFindManyArgs } from "./InterestFindManyArgs";
import { InterestWhereUniqueInput } from "./InterestWhereUniqueInput";
import { InterestUpdateInput } from "./InterestUpdateInput";
import { UserInterestFindManyArgs } from "../../userInterest/base/UserInterestFindManyArgs";
import { UserInterest } from "../../userInterest/base/UserInterest";
import { UserInterestWhereUniqueInput } from "../../userInterest/base/UserInterestWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InterestControllerBase {
  constructor(
    protected readonly service: InterestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Interest })
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInterest(
    @common.Body() data: InterestCreateInput
  ): Promise<Interest> {
    return await this.service.createInterest({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Interest] })
  @ApiNestedQuery(InterestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async interests(@common.Req() request: Request): Promise<Interest[]> {
    const args = plainToClass(InterestFindManyArgs, request.query);
    return this.service.interests({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async interest(
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<Interest | null> {
    const result = await this.service.interest({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInterest(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() data: InterestUpdateInput
  ): Promise<Interest | null> {
    try {
      return await this.service.updateInterest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInterest(
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<Interest | null> {
    try {
      return await this.service.deleteInterest({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/userInterests")
  @ApiNestedQuery(UserInterestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserInterest",
    action: "read",
    possession: "any",
  })
  async findUserInterests(
    @common.Req() request: Request,
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<UserInterest[]> {
    const query = plainToClass(UserInterestFindManyArgs, request.query);
    const results = await this.service.findUserInterests(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        interest: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userInterests")
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "update",
    possession: "any",
  })
  async connectUserInterests(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserInterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userInterests: {
        connect: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userInterests")
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "update",
    possession: "any",
  })
  async updateUserInterests(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserInterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userInterests: {
        set: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userInterests")
  @nestAccessControl.UseRoles({
    resource: "Interest",
    action: "update",
    possession: "any",
  })
  async disconnectUserInterests(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserInterestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userInterests: {
        disconnect: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
